### ISSUE TITLE
Adding Silesian translation file

### ISSUE THREAD

**Issue by gkkulik** [elementary/switchboard-plug-wallet#2]
Hi, could you add translation files for Silesian?

ISO 639-3: szl
Plurals: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);

Thank you!

**Comment by peteruithoven** [comment]
Not sure what you mean but he's the info on contributing to translations: https://elementary.io/get-involved#translations

**Comment by gkkulik** [comment]
@peteruithoven Silesian translations are not showing in Weblate because of missing files, so Daniel asked me to file an issue everywhere where there is a missing one.

**Comment by comradekingu** [comment]
All that is needed is adding one Silesian resource with the language consistency plugin turned on.
